FROM so77id/tensorflow-opencv-py3:latest-gpu
MAINTAINER Miguel Rodriguez <m.rodriguezs1990@gmail.com>

RUN pip3 install moviepy requests
RUN python3 -c 'import moviepy.editor as mpy'

RUN pip3 install git+https://github.com/wookayin/tensorflow-plot.git@master

RUN pip install slackclient

RUN pip3 install torch torchvision

RUN pip3 install tensorboardX

CMD ["/bin/bash"]
